name: CI?CD to EKS

on:
  push:
    branches:["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu:latest
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
          with:
            aws-region: us-east-2
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Update Kubeconfig
        run: eksctl utils write-kubeconfig --cluster diogo-ft-cluster --region us-east-2
 
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f .
